### PR TITLE
populate native source

### PR DESCRIPTION
**Pull request by ebarboni**

### CODE REVIEW

**Comment by ebarboni** [comment]
Hi this is early setup trying to preserve history for native file for windows installer engine. 
To make some fix available for the build.

Does it seems correct to you ? (Not building yet)

**Comment by ebarboni** [comment]
@matthiasblaesing it's an git-filter on branch to preserve history. (a bit like this https://gist.github.com/wevtimoteo/a6f4b0837cdc3749dd6b), that was the main objective

It doesn't build now, just file placement. I intend to use same build system as https://github.com/apache/netbeans-native-launchers.

I focus on windows but maybe linux/unix could be done this way.
(tested cleaner.Exe in local and seems to work)

I should once this is ready cleanup 
https://github.com/apache/netbeans/tree/master/nbi/engine
to prevent windows build.
And the should add this as external in (excluding the [nbi.engine-external-binaries-11](https://github.com/apache/netbeans/blob/master/harness/libs.nbi.engine/external/nbi.engine-external-binaries-11-license.txt) windows part 
https://github.com/apache/netbeans/tree/master/harness/libs.nbi.engine

**Comment by matthiasblaesing** [comment]
Looks ok to me. I assume the removal of everything non-windows is intentional and the reason is, that the unix parts can be easier build than the windows parts?!

**Review by matthiasblaesing — APPROVED** [review]

**Comment by ebarboni** [comment]
@matthiasblaesing sorry for late response though I've pressed the button last week. I will redo a PR with all the native part, building what could be built.

**Pull request closed without merging**
